version: '3.7'
services:
  db:
    image: mongo:4.4.17
    restart: unless-stopped
    ports:
      - "27017:27017"
    container_name: mongodb
    volumes:
      - ~/mongodata:/data/db
    networks:
      - dmims
#external_links: 
#  - tmrweb
  proxy:
    build:
      context: .
      dockerfile: Dockerfile
    image: cds_hooks_ms
    container_name: hooks_manager_service
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - MONGODB_HOST=mongodb
      - MONGODB_PORT=27017
      - MONGODB_LOGS=hooks_ms_log
      - MONGODB_CIG_MODEL=tmr
      - MONGODB_NONCIG_DB_NAME=non-cig
      - CDS_SERVICES_MS_HOST=services_manager_service
      - CDS_SERVICES_MS_PORT=3010
      - SNOMEDCT_BASE_URL=snowstorm-fhir.snomedtools.org
      - PROXY_PORT=3000
    links:
      - db
    depends_on:
      - db
    #  - .:/home/node/app
    #  - node_modules:/home/node/app/node_modules
    networks:
      - dmims
    #  - tmrwebx_cig_handler
    #command: ./wait-for.sh db:27017 -- /home/node/app/node_modules/.bin/nodemon app.js
networks:
  dmims: {}
 # tmrwebx_cig_handler:
  #  external: true

#volumes: 
# - ~/mongodata:
